---
# installs dev dependencies

- name: Update system
  dnf:
    name: "*"
    state: latest

- name: Install dependencies
  vars:
    packages:
  dnf:
    name:
      - cmake
      - gcc-c++
      - make
      - python3-devel
      - git-core
      - zlib
      - zlib-devel
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - curl
      - sqlite-devel
      - python-pip
      - python3-pip
      - stow
      - fish
      - rxvt-unicode
      - tmux
      - libselinux-python
      - vim
      - util-linux-user
    state: present
