---
# Ruby / Rails setup

- name: Check if rbenv is installed
  stat:
    path: ~/.rbenv
  register: rbenv_path

- name: Check if ruby is installed
  stat:
    path: ~/.rbenv/shims/ruby
  register: ruby_installed

- name: Pull rbenv
  git:
    repo: https://github.com/rbenv/rbenv
    dest: ~/.rbenv
    clone: yes
  when: rbenv_path.stat.isdir is not defined

- name: Create plugins directory
  file:
    path: ~/.rbenv/plugins
  when: rbenv_path.isdir is defined

- name: Pull ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install ruby
  shell: "~/.rbenv/bin/rbenv install {{ ruby_version }}"
  when: not ruby_installed.stat.exists

- name: Install bundler
  shell: "~/.rbenv/bin/rbenv global {{ ruby_version }}; ~/.rbenv/shims/gem install bundler"
  when: not ruby_installed.stat.exists

- name: Install rails
  shell: "~/.rbenv/bin/rbenv global {{ ruby_version }}; ~/.rbenv/shims/gem install rails"
  when: ruby_installed.stat.exists
